# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g yarn
    yarn install
  displayName: 'yarn install and build'

# install & prepare snyk
- script: |
    npm install -g snyk snyk-to-html
    mkdir html
    snyk auth $(SNYK_TOKEN_2)
    # explicitly allow scripts to continue if errors occur
    set +e
  displayName: 'snyk install & auth'

# snyk code to html
- script: |
    snyk code test --sarif-file-output=results.sarif --report --project-name="Tesla-Web-Beta-Release-Code" || true
    ls -la results.sarif || true
    RESULT=$?
    snyk-to-html -o $(Build.ArtifactStagingDirectory)/results-code.html < results.sarif
    exit $RESULT
  continueOnError: true
  displayName: 'snyk code report html and UI'

# snyk open source to html
- script: |
    snyk test --json-file-output=results.json || true
    RESULT=$?
    snyk-to-html -o $(Build.ArtifactStagingDirectory)/results-open-source.html < results.json
    exit $RESULT
  continueOnError: true
  displayName: 'snyk open source report html'

  # snyk container to html
  # NOTE: Change the image name
- script: |
    snyk container test ucrew/tesla-web:latest --file=Dockerfile --json-file-output=results.json
    RESULT=$?
    snyk-to-html -o $(Build.ArtifactStagingDirectory)/results-container.html < results.json
    exit $RESULT
  continueOnError: true
  displayName: 'snyk container report html'

# snyk open source to UI
- script: |
    snyk monitor --project-name=Tesla-Web-Beta-Release-OSS || true
    RESULT=$?
    exit $RESULT
  continueOnError: true
  displayName: 'snyk open source monitor'

# Publish html
- task: PublishHtmlReport@1
  condition: succeededOrFailed()
  inputs:
    reportDir: $(Build.ArtifactStagingDirectory)/results-code.html
    tabName: 'Snyk Code'

- task: PublishHtmlReport@1
  condition: succeededOrFailed()
  inputs:
    reportDir: $(Build.ArtifactStagingDirectory)/results-open-source.html
    tabName: 'Snyk Open Source'

- task: PublishHtmlReport@1
  condition: succeededOrFailed()
  inputs:
    reportDir: $(Build.ArtifactStagingDirectory)/results-container.html
    tabName: 'Snyk Container'